[project]
name = "kahnemanbench"
version = "0.1.0"
description = "An AI benchmark for Kahneman impersonation and behavioral science taste rating."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.40.0",
    "fire>=0.7.0",
    "litellm>=1.54.1",
    "openai>=1.57.2",
    "python-dotenv>=1.0.1",
    "weave>=0.51.23",
]
