# Quick test configuration - fast evaluation with limited models
name: "Quick Test"
description: "Fast pipeline test with 2 models for development/testing"

# Models for impersonation generation
models:
  - "gpt-4o"
  - "claude-3-5-sonnet"

# Model for rating evaluation  
rater_model: "gpt-4o"

# Dataset path
dataset_path: "02_curated_datasets/kahneman_dataset_v1.json"

# Pipeline options
skip_impersonation: false
rating_dataset_path: null

# Weave project settings
project_suffix: "_quick_test"